config/routes.rb
Rails.application.routes.draw do
  resources :warriors

  devise_for :users
  root to: 'static_pages#battleground'

  #static_pages
  get  '/battleground', to: 'static_pages#battleground', as: :battleground
  get  '/stats', to: 'static_pages#stats', as: :stats

  get '/statistical', to: 'warriors#statistical'

  #battles
  post  '/battle', to: 'battles#battle'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/battle.rb
class Battle < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/warrior.rb
class Warrior < ApplicationRecord
  mount_uploader :image, WarriorUploader

  validates :name, presence: true
  validates :image, presence: true
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/battles_controller.rb
class BattlesController < ApplicationController
  include WarrioresHelper

  def battle
    first_warrior = Warrior.find(params[:first_warrior_id])
    second_warrior = Warrior.find(params[:second_warrior_id])
    battle = Battle.new(warrior_one_id: first_warrior.id,warrior_two_id: second_warrior.id)
    first_warrior_performances = first_warrior.armor + first_warrior.strength
    second_warrior_performances = second_warrior.armor + second_warrior.strength
    if first_warrior_performances > second_warrior_performances
      battle.winner_id = first_warrior.id
      check_warrior_level(first_warrior,3)
    elsif first_warrior_performances < second_warrior_performances
      battle.winner_id = second_warrior.id
      check_warrior_level(first_warrior,1)
    elsif first_warrior_performances == second_warrior_performances
      if rand(1..2) == 1
        battle.winner_id = first_warrior.id
        check_warrior_level(first_warrior,3)
      else
        battle.winner_id = second_warrior.id
        check_warrior_level(first_warrior,1)
      end
    end
    battle.save
    render :json => battle.winner_id
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def battleground
    session[:menu] = "battleground"
    @current_user_warriors = Warrior.where(creater_id: current_user.id) if user_signed_in?
    @enemy_warriors = Warrior.where(creater_id: nil)
    @enemy_warriors += Warrior.where('creater_id != ?', current_user.id) if user_signed_in?
  end
end

app/controllers/warriors_controller.rb
class WarriorsController < ApplicationController
  before_action :set_warriore, only: [:show, :edit, :update, :destroy]
  # GET /warriores
  # GET /warriores.json
  def index
    session[:menu] = "index"
    @current_user_warriors = Warrior.where(creater_id: current_user.id) if user_signed_in?
    @enemy_warriors = Warrior.where(creater_id: nil)
    @enemy_warriors += Warrior.where('creater_id != ?', current_user.id) if user_signed_in?
    render template: "warrior/index"
  end

  # GET /warriores/1
  # GET /warriores/1.json
  def show
    @creater_email = User.find( @warrior.creater_id).email if @warrior.creater_id
    render template: "warrior/show"
  end

  # GET /warriores/new
  def new
    @warrior = Warrior.new
    render template: "warrior/new"
  end

  # GET /warriores/1/edit
  def edit
    @warrior = set_warriore()
    render template: "warrior/edit"
  end

  # POST /warriores
  # POST /warriores.json
  def create
    @warrior = Warrior.new(warriore_params)
    respond_to do |format|
      if @warrior.save
        format.html { redirect_to @warrior, notice: 'Warrior was successfully created.' }
        format.json { render :show, status: :created, location: @warrior }
      else
        format.html { render :new }
        format.json { render json: @warrior.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /warriores/1
  # PATCH/PUT /warriores/1.json
  def update
    respond_to do |format|
      if @warrior.update(warriore_params)
        format.html { redirect_to @warrior, notice: 'Warrior was successfully updated.' }
        format.json { render :show, status: :ok, location: @warrior }
      else
        format.html { render :edit }
        format.json { render json: @warrior.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /warriores/1
  # DELETE /warriores/1.json
  def destroy
    @warrior.destroy
    respond_to do |format|
      format.html { redirect_to warriors_path, notice: 'Warrior was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def statistical
    data = []
    last_combats = []
    warrior = set_warriore
    battles = Battle.where(warrior_one_id: warrior.id)
    victory = 0
    defeat = 0
    battles.each do |battle|
      if battle.winner_id == warrior.id
        result = 'victory'
        victory += 1
      else
        result = 'defeat'
        defeat += 1
      end
      last_combats << {enemy_name: Warrior.find(battle.warrior_two_id).name, result: result}
    end
    statistical = {all: battles.length, victory: victory, defeat: defeat}
    data << statistical
    data << last_combats
    render :json => data
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_warriore
      @warrior = Warrior.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def warriore_params
      params.require(:warrior).permit(:creater_id,:name, :description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/warriores_helper.rb
module WarrioresHelper

  def check_warrior_level(warrior,points)
    if points
      warrior.points += points
    end
    warrior_points = warrior.points
    if warrior_points >= 20 && warrior_points < 45
      warrior.level = 2
      warrior.armor = 4
      warrior.strength = 4
    elsif warrior_points >= 45 && warrior_points < 70
      warrior.level = 3
      warrior.armor = 6
      warrior.strength = 6
    elsif warrior_points >= 70 && warrior_points < 136
      warrior.level = 4
      warrior.armor = 8
      warrior.strength = 8
    elsif warrior_points >= 136
      warrior.level = 5
      warrior.armor = 10
      warrior.strength = 10
    end
    warrior.save
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Captain Contrat Battles</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container">
      <div class="row">
        <div class="col-md-3">
          <span style="margin-bottom:10px;display:block">
            <%if !user_signed_in?%>
              <%= link_to 'Connexion', user_session_path, class: "btn btn-outline-primary" %>
              <%= link_to 'Inscription', new_user_registration_path, class: "btn btn-outline-success" %>
            <%else%>
              <%= link_to current_user.email.upcase, edit_user_registration_path, class: "h6" %>
              <%= link_to "DEC", destroy_user_session_path, method: :delete, class: "h6 btn btn-primary" %>
            <%end%>
          </span>
          <div class="list-group">
            <%if session[:menu] == "battleground"%>
              <%= link_to 'Champ de bataille', battleground_path, class: "list-group-item list-group-item-action active" %>
              <%= link_to 'Guerriers', warriors_path, class: "list-group-item list-group-item-action"  %>
            <%else%>
              <%= link_to 'Champ de bataille', battleground_path, class: "list-group-item list-group-item-action " %>
              <%= link_to 'Guerriers', warriors_path, class: "list-group-item list-group-item-action active"  %>
            <%end%>
          </div>
        </div>
        <div class="col-md-9">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/static_pages/battleground.html.erb
<div class="row">
  <%if current_user%>
    <div class="col-md-3 battleground_warriors_case">
      <p class="h4 text-center">Mes guerriers</p>
      <%if @current_user_warriors.present?%>
        <%@current_user_warriors.each do |warrior|%>
          <div class="col-md-12 padding-none ">
            <div class="card">
              <span class=card-level><%=warrior.level%></span>
              <span class="card-image-min"  id="warrior<%=warrior.id%>"><%= image_tag(warrior.image_url, class: "card-img-top") %></span>
              <div class="card-body">
                <h5 class="card-title"><%=warrior.name%></h5>
                  <p class="h6 margin-none">Défense</p>
                  <div class="scale scale_min" id="scale_armor">
                    <%for i in 1..10%>
                      <%if i <= warrior.armor%>
                        <span class="active"></span>
                      <%else%>
                        <span></span>
                      <%end%>
                    <%end%>
                  </div>
                  <p class="h6 margin-none">Attaque</p>
                  <div class="scale scale_min" id="scale_strength">
                    <%for i in 1..10%>
                      <%if i <= warrior.strength%>
                        <span class="active"></span>
                      <%else%>
                        <span></span>
                      <%end%>
                    <%end%>
                  </div>
                <button data-id='<%=warrior.id%>' class="btn btn-primary my_warrior_choose">Choisir</button>
              </div>
            </div>
          </div>
        <%end%>
      <%else%>
        <div class="col-md-12">
          <p class="h4 text-center">Pas de Guerriers</p>
        </div>
      <%end%>
    </div>
    <div class="col-md-6">
      <p class="h4 text-center">Combat</p>
      <span class="batlle_span">
        <div class="row">
          <div class="col-md-2"></div>
          <div class="col-md-8 my_warrior_case"></div>
          <div class="col-md-2"></div>
        </div>
        <p class="h4 text-center">VS</p>
        <div class="row">
          <div class="col-md-2"></div>
          <div class="col-md-8 enemy_case"></div>
          <div class="col-md-2"></div>
        </div>
        <button class="battle btn btn-primary lg_btn_center" style="display:none">COMBATTRE</button>
      </span>
    </div>
    <div class="col-md-3 battleground_warriors_case">
      <p class="h4 text-center">Ennemis</p>
      <%if @enemy_warriors.present?%>
        <%@enemy_warriors.each do |warrior|%>
          <div class="col-md-12 padding-none">
            <div class="card" >
              <span class=card-level><%=warrior.level%></span>
              <span class="card-image-min" id="warrior<%=warrior.id%>"><%= image_tag(warrior.image_url, class: "card-img-top") %></span>
              <div class="card-body">
                <h5 class="card-title"><%=warrior.name%></h5>
                <p class="h6 margin-none">Défense</p>
                <div class="scale scale_min" id="scale_armor">
                  <%for i in 1..10%>
                    <%if i <= warrior.armor%>
                      <span class="active"></span>
                    <%else%>
                      <span></span>
                    <%end%>
                  <%end%>
                </div>
                <p class="h6 margin-none">Attaque</p>
                <div class="scale scale_min" id="scale_strength">
                  <%for i in 1..10%>
                    <%if i <= warrior.strength%>
                      <span class="active"></span>
                    <%else%>
                      <span></span>
                    <%end%>
                  <%end%>
                </div>
                <button  data-id='<%=warrior.id%>' class="btn btn-primary enemy_choose">Choisir</button>
              </div>
            </div>
          </div>
        <%end%>
      <%else%>
        <div class="col-md-12">
          <p class="h4 text-center">Pas de Guerriers</p>
        </div>
      <%end%>
    </div>
  <%else%>
  <p class="h2 text-center">Créez un compte et puis un Guerrier pour pouvoir devenir the GOD de CAPTAIN CONTRAT BATTLES</p>
  <%end%>
</div>
<script>
  var first_warrior_id
  var second_warrior_id

  function check_warriors(){
    console.log(first_warrior_id + " " + second_warrior_id)
    if (first_warrior_id && second_warrior_id){
      $('.battle').css('display','block')
    }
  }

  $('.my_warrior_choose').click(function(){
    first_warrior_id = $(this).data('id')
    $('.my_warrior_case').html($('#warrior' + first_warrior_id).html())
    check_warriors()
  })

  $('.enemy_choose').click(function(){
    second_warrior_id = $(this).data('id')
    $('.enemy_case').html($('#warrior' + second_warrior_id).html())
    check_warriors()
  })

  $('.battle').click(function(){
    if (first_warrior_id && second_warrior_id){
      $.ajax({
        url: "/battle",
        type: 'post',
        data: 'first_warrior_id=' + first_warrior_id+ '&second_warrior_id=' + second_warrior_id,
        success: function(data) {
          $('.batlle_span').html('<p class="h4 text-center">GAGNANT</p><div class="col-md-12">' +$('#warrior' + data).html()+ '</div><button class="battle btn btn-primary lg_btn_center"><a href="/battleground">Nouveau combat</a></button>')
          first_warrior_id = 0
          second_warrior_id = 0
        }
      });
    }
  })
</script>

app/views/warrior/edit.html.erb
<%= form_with model: @warrior, class: "form-group" do |f| %>
  <div class="row">
    <div class="col-md-6">
      <%= f.hidden_field :creater_id, value: current_user.id%>
      <%= f.hidden_field :strength%>
      <%= f.hidden_field :armor%>
      <%= label_tag(:name, "Nom") %>
      <%= f.text_field :name, class: "form-control" %>
      <%= label_tag(:description, "Description") %>
      <%= f.text_area :description, class: "form-control"  %>
    </div>
    <div class="col-md-6">
      <%= f.file_field :image,class:"form-control-file" %>
    </div>
    <div class="col-md-12">
      <%= f.submit "Modifier", class:"btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/warrior/index.html.erb
<%= link_to 'Créer un guerrier',  new_warrior_path, class: "btn btn-primary btn-lg margin_10"  if current_user %>
<h2>Mes Guerriers</h2>
<div class="row">
  <%if @current_user_warriors.present?%>
    <%@current_user_warriors.each do |warrior|%>
      <div class="col-md-4" style="margin-bottom:15px">
        <div class="card">
          <span class=card-level><%=warrior.level%></span>
          <span class="card-image"><%= image_tag(warrior.image_url, class: "card-img-top") %></span>
          <div class="card-body">
            <h5 class="card-title"><%=warrior.name%></h5>
            <p class="h6 margin-none">Défense</p>
            <div class="scale scale_big" id="scale_armor">
              <%for i in 1..10%>
                <%if i <= warrior.armor%>
                  <span class="active"></span>
                <%else%>
                  <span></span>
                <%end%>
              <%end%>
            </div>
            <p class="h6 margin-none">Attaque</p>
            <div class="scale scale_big" id="scale_strength">
              <%for i in 1..10%>
                <%if i <= warrior.strength%>
                  <span class="active"></span>
                <%else%>
                  <span></span>
                <%end%>
              <%end%>
            </div>
            <p class="card-text"><%=(warrior.description).truncate(27)%></p>
            <%= link_to 'Voir le guerrier',  warrior_path(warrior), class: "btn btn-primary"  %>
          </div>
        </div>
      </div>
    <%end%>
  <%else%>
    <div class="col-md-12">
      <p class="h4 text-center">Pas de Guerriers</p>
    </div>
  <%end%>
</div>
<h2>Ennemis</h2>
<div class="row">
  <%if @enemy_warriors.present?%>
    <%@enemy_warriors.each do |warrior|%>
      <div class="col-md-4" style="margin-bottom:15px">
        <div class="card">
          <span class=card-level><%=warrior.level%></span>
          <span class="card-image"><%= image_tag(warrior.image_url, class: "card-img-top") %></span>
          <div class="card-body">
            <h5 class="card-title"><%=warrior.name%></h5>
            <p class="h6 margin-none">Défense</p>
            <div class="scale scale_big" id="scale_armor">
              <%for i in 1..10%>
                <%if i <= warrior.armor%>
                  <span class="active"></span>
                <%else%>
                  <span></span>
                <%end%>
              <%end%>
            </div>
            <p class="h6 margin-none">Attaque</p>
            <div class="scale scale_big" id="scale_strength">
              <%for i in 1..10%>
                <%if i <= warrior.strength%>
                  <span class="active"></span>
                <%else%>
                  <span></span>
                <%end%>
              <%end%>
            </div>
            <p class="card-text"><%=(warrior.description).truncate(80)%></p>
            <%= link_to 'Voir le guerrier',  warrior_path(warrior), class: "btn btn-primary"  %>
          </div>
        </div>
      </div>
    <%end%>
  <%else%>
    <div class="col-md-12">
      <p class="h4 text-center">Pas de Guerriers</p>
    </div>
  <%end%>
</div>

app/views/warrior/new.html.erb
<p class="h2 text-center">Nouveux guerrier</p>
<%= form_with model: @warrior, class: "form-group" do |f| %>
  <div class="row">
    <div class="col-md-6">
      <%= f.hidden_field :creater_id, value: current_user.id%>
      <%= label_tag(:name, "Name") %>
      <%= f.text_field :name, class: "form-control" %>
      <%= label_tag(:description, "Description") %>
      <%= f.text_field :description, class: "form-control"  %>
    </div>
    <div class="col-md-6">
      <%= f.file_field :image,class:"form-control-file" %>
    </div>
    <div class="col-md-12 margin_10">
      <%= f.submit "Créer", class:"btn btn-primary" %>
    </div>
  </div>
<% end %>
<script>


  $('#remakeQuiz').click(function(){
    cleanResponses()
    navigation_loading("begin",null,null)
  })

  $(".rate_training a").each(function(event) {
    $(this).click(function(){
      $("#goTraining").prop('disabled', false)
      rates($(this).index())
    })
  })

  function rates(index){
    count_star = index + 1
    for(i=0;i<=5;i++ ){
        $(".rate_training a:eq("+i+")").find("svg").attr('class',"fal fa-star")
    }
    for(i=0;i<=index;i++ ){
        $(".rate_training a:eq("+i+")").find("svg").attr('class',"fas fa-star")
    }
  }

</script>

app/views/warrior/show.html.erb
<script>
  $('.last_combats').val('')
</script>
<div class="row">
  <div class="col-md-12 margin_10">
    <p class="h2 text-center"><%=@warrior.name%></p>
  </div>
  <div class="col-md-6">
    <span><%= image_tag(@warrior.image_url, class: "card-img-top") %></span>
  </div>
  <div class="col-md-6">
    <div class="row">
      <div class="col-md-12">
        <p class="h5">Description</p>
        <p style="overflow:auto;"><%=@warrior.description%></p>
      </div>
      <div class="col-md-6">
        <p class="h5">Niveau</p>
        <p style="overflow:auto;"><%=@warrior.level%></p>
      </div>
      <div class="col-md-6">
        <p class="h5">Points</p>
        <p style="overflow:auto;"><%=@warrior.points%></p>
      </div>
      <div class="col-md-6">
        <p class="h5 margin-none">Défense</p>
        <div class="scale scale_min" >
          <%for i in 1..10%>
            <%if i <= @warrior.armor%>
              <span class="active"></span>
            <%else%>
              <span></span>
            <%end%>
          <%end%>
        </div>
      </div>
      <div class="col-md-6">
        <p class="h5 margin-none">Attaque</p>
        <div class="scale scale_min">
          <%for i in 1..10%>
            <%if i <= @warrior.strength%>
              <span class="active"></span>
            <%else%>
              <span></span>
            <%end%>
          <%end%>
        </div>
      </div>
      <%if @warrior.creater_id%>
        <div class="col-md-6">
          <p class="h5 margin-none">Créateur</p>
          <p><%=@creater_email%></p>
        </div>
      <%end%>
    </div>
  </div>
  <%if @warrior.creater_id%>
    <div class="col-md-12 margin_10" style="max-height:400px;overflow:auto">
      <p class="h4">Statistique de combats</p>
      <div class='row statistical'>
        <div class="col-md-4">
          <p class="h5">Tous</p>
          <div class="card" >
            <div class="card-body text-center all h5 margin-none"></div>
          </div>
        </div>
        <div class="col-md-4">
          <p class="h5">Virctoires</p>
          <div class="card">
              <div class="card-body text-center victorys h5 margin-none"></div>
          </div>
        </div>
        <div class="col-md-4">
          <p class="h5">Défaites</p>
          <div class="card">
            <div class="card-body text-center defeats h5 margin-none"></div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-12 margin_10" >
      <p class="h4">Les dérniers combats</p>
      <div style="max-height:400px;overflow:auto" class='row last_combats'></div>
    </div>
  <%end%>
  <div class="col-md-12 margin_10">
    <%= link_to 'Modifier',  edit_warrior_path(@warrior), class: "btn btn-primary" if  @warrior.creater_id && @warrior.creater_id == current_user.id%>
    <%= link_to 'Supprimer',  "/warriors/#{@warrior.id}",method: :delete, class: "btn btn-primary" if  @warrior.creater_id && @warrior.creater_id == current_user.id%>
  </div>
</div>
<script>
  $(document).ready(function() {

    $.ajax({
      url: "/statistical",
      type: 'get',
      data: 'id=<%=@warrior.id%>',
      success: function(data) {
        last_combats = data[1]
        statistical = data[0]
        $('.all').html(statistical['all'])
        $('.victorys').html(statistical['victory'])
        $('.defeats').html(statistical['defeat'])
        for(i = 0; i < last_combats.length;i++){
          var color
          if (last_combats[i]["result"] == 'victory'){
            color = "green"
          }else{
            color = "red"
          }
          $('.last_combats').append('<div class="col-md-3" style="margin-bottom:15px;color: white;"><div class="card" style="background:'+color+'"><div class="card-body text-center">'+last_combats[i]["enemy_name"]+'</div></div></div>')
        }
      }
    });
  })
</script>